name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
  
    
    - name: Run tests with pytest
      run: |
        uv run pytest
      env:
        PYTHONPATH: ${{ github.workspace }}
        OPENAI_API_KEY: "test"